workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: buynow codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: "com.manz2.buynow"
        APP_STORE_APPLE_ID: "6756811129"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
        automatic_signing: true

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ipa --release

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false